#Image bind9
FROM ubuntu/apache2

#Récupéré et mettre à jour les fichers de configurations
RUN apt-get update && apt-get install -y bind9

#Copier les fichier dns dans etc/bind
COPY apache2.conf /etc/apache2/

#Crée les fichiers www


#Installer nano et vim
RUN apt-get install vim nano -y

#Ouvrir le port 53 avec tcp et udp
EXPOSE 80/tcp

#Lancer le service bind9
#CMD ["/etc/init.d/apache2", "start"]